✨ Add ArchNexus and IArchNexus
arch-protocol/chambers-peripherals pull request #29
Opened 2024-02-28 15:40 UTC by Gaonuk

2024-02-28 15:47 UTC, juansjimenez requested changes

2024-02-28 15:47 UTC, juansjimenez commented on src/ArchNexus.sol
> +     * Transfer all stucked Ether to the owner of the contract
```suggestion
     * Transfer all stuck Ether to the owner of the contract
```

2024-02-28 15:47 UTC, juansjimenez commented on src/ArchNexus.sol
> +     * Transfer all stucked Ether to the owner of the contract
What about Polygon?

2024-02-28 15:47 UTC, juansjimenez commented on src/ArchNexus.sol
> +                _target, type(uint256).max - currentAllowance
Why not 
```suggestion
                _target, _requiredAmount - currentAllowance
```

2024-02-28 15:47 UTC, juansjimenez commented on src/ArchNexus.sol
> +
Podriamos aca `decreaseAllowance` tambien, a 0, al `allowanceTarget` post instruction no?

2024-02-28 16:11 UTC, JPSCHELE reviewed
Agreguemos eventos al final de las funciones para poder después hacer analytics en dune.

2024-02-28 16:11 UTC, JPSCHELE commented on src/ArchNexus.sol
> +        address _finalToken
es mala idea poner el final amount ? como para armar un last check ? 
viendo la función como que me falta visualmente el final amount.

2024-02-28 16:11 UTC, JPSCHELE commented on src/ArchNexus.sol
> +
esto lo hicimos para ahorrar gas, la idea es que este increase allowance se haga prácticamente una vez por token.

2024-02-28 16:11 UTC, JPSCHELE commented on src/ArchNexus.sol
> +                _target, type(uint256).max - currentAllowance
idem comment de antes

2024-02-28 18:00 UTC, juansjimenez commented on src/ArchNexus.sol
> +     * Transfer all stucked Ether to the owner of the contract
No me refiero no hay Archemists en Polygon?

2024-02-28 18:00 UTC, juansjimenez commented on src/ArchNexus.sol
> +
An key

2024-02-28 18:31 UTC, JPSCHELE approved these changes

2024-03-01 13:01 UTC, juansjimenez approved these changes

2024-03-01 13:01 UTC, merged